[tool.poetry]
name = "osw-builder"
version = "0.1.0"
description = ""
authors = ["Mathieu Tarral <mathieu.tarral@protonmail.com>"]
readme = "README.md"
include = [
    "osw_builder/packer-templates/**",
    "osw_builder/default_settings.yaml",
]

[tool.poetry.dependencies]
python = "^3.10"
docopt = "^0.6.2"
pyyaml = "^6.0.1"
libvirt-python = "^10.3.0"
guestfs = { url = "https://download.libguestfs.org/python/guestfs-1.40.2.tar.gz" }
neogit = { git = "https://github.com/OSWatcher/neogit.git", tag = "v0.10.1" }
winupdate = { git = "https://github.com/OSWatcher/pywinupdate.git" }
plugins = { git = "https://github.com/OSWatcher/grapheos-plugins.git", rev = "v0.7" }
dynaconf = "^3.2.5"
python-hcl2 = "^4.3.4"
docker = "^7.1.0"
appdirs = "^1.4.4"
attrs = "^23.2.0"

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.26.1"
flake8 = "^7.0.0"
mypy = "^1.10.0"
isort = "^5.13.2"
flake8-bugbear = "^24.4.26"
black = "^24.4.2"
pytest = "8.2.2"


[tool.poetry.group.docs.dependencies]
sphinx = "7.2.6"
furo = "^2024.8.6"
myst-parser = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
osw-builder = "osw_builder.__main__:entrypoint"
osw-capture-tool = "osw_builder.capture:main"

[tool.poe.tasks]
fmt = "black ."
fmt-check = "black --check ."
_flake8 = "flake8 --show-source --statistics ."
_isort = "isort ."
lint = ["_flake8", "_isort"]
typecheck = "mypy ."
ccode = ["fmt", "lint"]
unit_test = "pytest"
docs = "sphinx-build docs/source docs/build"


[tool.black]
line-length = 120
extend-exclude = "(^/.venv|^/docs/)"

[tool.isort]
profile = "black"
line_length = 120
skip = ["osw_builder/packer-templates", ".venv"]

[tool.pytest.ini_options]
norecursedirs = [".venv"]

[tool.mypy]
# exclude vendor folder
exclude = [".venv"]
