[tool.poetry]
name = "osw-builder"
version = "0.1.0"
description = ""
authors = ["Mathieu Tarral <mathieu.tarral@protonmail.com>"]
readme = "README.md"
include = [
    "osw_builder/packer-templates/**",
    "osw_builder/default_settings.yaml",
]

[tool.poetry.dependencies]
python = "^3.10"
docopt = "^0.6.2"
pyyaml = "^6.0.1"
libvirt-python = "^10.3.0"
guestfs = { url = "https://download.libguestfs.org/python/guestfs-1.40.2.tar.gz" }
neogit = { path = "vendor/neogit" }
oswatcher = { path = "vendor/oswatcher" }
pywinupdate = { path = "vendor/pywinupdate" }
dynaconf = "^3.2.5"

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.26.1"
flake8 = "^7.0.0"
mypy = "^1.10.0"
isort = "^5.13.2"
flake8-bugbear = "^24.4.26"
black = "^24.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
osw-builder = "osw_builder.__main__:entrypoint"

[tool.poe.tasks]
flake8 = "flake8 --show-source --statistics"
isort = "isort --line-length 120 ."
lint.shell = "poe flake8 && poe isort"
format = "black --line-length 120 ."
typecheck = "mypy ."

[tool.black]
exclude = '''
/(
    vendor
)/
'''
