name: "Setup Python and Poetry"
description: "Installs Python and Poetry with caching"

inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.11"
  poetry-version:
    description: "Poetry version to install"
    required: false
    default: "2.1.4"
  minio_secret:
    description: "Minio admin password"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Acquire Lock
      run: |
        LOCK_FILE="/tmp/github_action_lock"
        while ! mkdir "$LOCK_FILE" 2>/dev/null; do
          echo "Waiting for lock..."
          sleep $[ ( $RANDOM % 10 )  + 1 ]s
        done
        echo "Lock acquired"
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
      if: ${{ !env.ACT }}

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1.4.1
      with:
        version: ${{ inputs.poetry-version }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
        installer-parallel: true

    - name: Release Lock
      if: always()
      run: |
        rm -rf "/tmp/github_action_lock"
        echo "Lock released"
      shell: bash

    - name: Configure production environment
      if: ${{ !env.ACT }}
      run: |
        echo "NEOGIT_OBJECT__PROVIDER=minio" >> $GITHUB_ENV
        echo "NEOGIT_OBJECT__KEY=minioadmin" >> $GITHUB_ENV
        echo "NEOGIT_OBJECT__SECRET_KEY=${{ inputs.minio_secret }}" >> $GITHUB_ENV
        echo "NEOGIT_OBJECT__HOST=127.0.0.1" >> $GITHUB_ENV
        echo "NEOGIT_OBJECT__PORT=9000" >> $GITHUB_ENV
        echo "NEOGIT_OBJECT__SECURE=false" >> $GITHUB_ENV
      shell: bash

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root
      shell: bash

    - name: Install project
      run: poetry install --no-interaction
      shell: bash
