name: Builder

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10080
    steps:
      - name: Cleanup
        run: rm -rf *

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install Packer and vagrant
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/hashicorp.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y packer vagrant

      - name: Enforce setuid on qemu bridge helper
        run: sudo chmod u+s /usr/lib/qemu/qemu-bridge-helper

      - name: Ensure /etc/qemu/bridge.conf exists
        run: |
          # ensure /etc/qemu/bridge.conf exists and create the directory if needed
          # ensure the content is "allow virbr0"
          if [ ! -f /etc/qemu/bridge.conf ]; then
            sudo mkdir -p /etc/qemu
            echo "allow virbr0" | sudo tee /etc/qemu/bridge.conf
          fi

      - name: Ensure vmlinuz is readable for libguestfs supermin
        run: sudo chmod 644 /boot/vmlinuz

      - name: Ensure vagrant-libvirt
        run: vagrant plugin install vagrant-libvirt

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install poetry==1.8.3

      - name: Install dependencies
        run: poetry install

      - name: build
        run: poetry run osw-builder --only-serie windows-10 --updates=yes --search-updates=yes --var cpus=4
        env:
          PACKER_LOG: 1
          NEOGIT_OBJECT__SECRET_KEY: ${{ secrets.MINIO_ADMIN_PASSWD }}
          PACKER_CACHE_DIR: /home/ops/.cache/packer
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: Upload packer-build.log
        uses: actions/upload-artifact@v4
        with:
          name: packer-build-log
          path: packer-build.log
        if: always()
