name: Capture OS

on:
  workflow_call:
    inputs:
      os_name:
        type: string
        required: true
        description: 'Name of the OS to capture'

jobs:
  capture:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup environment for Packer and Vagrant
        if: ${{ !env.ACT }}
        uses: ./.github/actions/setup-packer-vagrant

      - name: Setup Python and Poetry
        uses: ./.github/actions/setup-python-poetry

      - name: Capture OS
        run: poetry run osw-builder capture_os ${{ inputs.os_name }} --var cpus=4

      - name: Upload packer-build.log
        uses: actions/upload-artifact@v4
        with:
          name: packer-build-log
          path: packer-build.log
        if: always()
