name: Capture OS

on:
  workflow_call:
    inputs:
      os_name:
        type: string
        required: true
        description: 'Name of the OS to capture'
      before:
        type: string
        required: false
        description: 'Commit to link the new commit to'
      search_updates:
        type: string
        required: false
        description: 'Search for updates'
        default: 'true'
      skip_compaction:
        type: boolean
        required: false
        description: 'Skip compaction'
        default: false
      branch_name:
        type: string
        required: false
        description: 'Neogit branch to commit to'

jobs:
  capture:
    runs-on: self-hosted

    steps:
      - name: Cleanup
        run: rm -rf *

      - run: |
          if [ -z "${{ secrets.GHCR_TOKEN }}" ]; then
            echo "Missing GHCR token"
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup environment for Packer and Vagrant
        if: ${{ !env.ACT }}
        uses: ./.github/actions/setup-packer-vagrant

      - name: Setup Python and Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          pat_token: ${{ secrets.PAT_TOKEN }}
          minio_secret: ${{ secrets.MINIO_ADMIN_PASSWD }}

      - name: Capture OS
        run: poetry run osw-builder capture_os "${{ inputs.os_name }}" --var cpus=4 --before="${{ inputs.before }}" --search-updates="${{ inputs.search_updates }}" --var skip_compaction=${{ inputs.skip_compaction }} --branch="${{ inputs.branch_name }}" -d
        env:
          PACKER_LOG: 1
          PACKER_CACHE_DIR: $HOME/.cache/packer
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: Upload packer-build.log
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.os_name }}-${{ github.run_attempt }}-packer-build.log
          path: packer-build.log
        if: ${{ !env.ACT && hashFiles('packer-build.log') != '' }}

      - name: Upload vagrant.log
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.os_name }}-${{ github.run_attempt }}-vagrant.log
          path: vagrant.log
        if: ${{ !env.ACT && hashFiles('vagrant.log') != ''}}
