name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    strategy:
      matrix:
        check: ['fmt-check', 'lint', 'typecheck']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT_TOKEN}}

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Poetry
        run: pip install poetry==1.8.2

      - name: Run check ${{ matrix.check }}
        run: |
          poetry install --only dev
          poetry run poe ${{ matrix.check }}

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dev image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: dev
          push: false
          load: true
          tags: osw-builder-dev
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.PAT_TOKEN }}

      - name: Run unit tests
        run: docker run --rm osw-builder-dev
